version: '3.9'
services:
    redis:
        image: redis/redis-stack-server
        ports:
          - "6379:6379"
    app:
      build:
        context: .
        dockerfile: ./Dockerfile.app
      ports:
        - "80:8080"
      depends_on:
        - redis