version: '3.9'
services:
    redis:
        image: redis/redis-stack-server
        ports:
          - "6379:6379"
        volumes:
          - redis_data:/data
    app:
      build:
        context: .
        dockerfile: ./Dockerfile.app
      ports:
        - "80:8080"
      depends_on:
        - redis
      environment:
        - KEYWORDS_STATS_REDIS_URL="redis://redis:6379"
      
volumes:
  redis_data: