# restapi-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keystat-app
spec:
  replicas: 1  # Start with 2 replicas
  selector:
    matchLabels:
      app: keystat-app
  template:
    metadata:
      labels:
        app: keystat-app
    spec:
      containers:
      - name: keystat-app
        image: mvkan/keywords-stats-app:latest   
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
        - name: KEYWORDS_STATS_REDIS_URL
          value: "redis://redis:6379"  # The name of the Redis service
        